experiment:
  source_dataset:
    class_name: MNIST
    path: ~/robust-domain-adaptation/dataset_registry/data/mnist
    train:
      name: MNIST-t
    validate:
      name: MNIST-v
  target_dataset:
    class_name: MNIST_M
    path: ~/robust-domain-adaptation/dataset_registry/data/mnistm
    train: 
      name: MNISTM-t
    validate:
      name: MNISTM-v
  models:
    - Discriminator
    - Generator
    - Classifier 
  routines:
    - train_pixel_da:
        discriminator: Discriminator
        generator: Generator
        classifier: Classifier
        source_train: MNIST-t
        target_train: MNISTM-t
        source_val: MNIST-v
        target_val: MNISTM-v
  global_params:
    num_epochs: 100
    batch_size: 64
    lr: 0.0002
    b1: 0.5
    b2: 0.999
    n_cpu: 8
    n_residual_blocks: 6
    latent_dim: 10
    img_size: 32
    channels: 3
    n_classes: 10
    class_names:
      - zero
      - one
      - two 
      - three 
      - four 
      - five 
      - six 
      - seven
      - eight
      - nine 