experiment:
  source_dataset:
    class_name: PACS_P
    path: /home/mielonen/robust-domain-adaptation/dataset_registry/data/pacs
    train:
      name: visdas-t
      transform_args:
        resizing: cen.crop
    validate:
      name: visdas-v
      transform_args: {}
  target_dataset:
    class_name: PACS_A
    path: /home/mielonen/robust-domain-adaptation/dataset_registry/data/pacs
    train: 
      name: visdar-t
      transform_args:
        resizing: cen.crop
    validate:
      name: visdar-v
      transform_args: {}
  models:
    - tlibClassifier
  routines:
    - train_mcc:
        classifier: tlibClassifier
        source_train: visdas-t
        target_train: visdar-t
        source_val: visdas-v
        target_val: visdar-v
  global_params:
    num_epochs: 15
    seed: 42
    iters_per_epoch: 400
    batch_size: 36
    lr: 0.002
    lr_gamma: 0.001
    lr_decay: 0.75
    momentum: 0.9
    test_size: 0.25
    weight_decay: 0.001
    trade_off: 1.0
    n_cpu: 8
    n_classes: None
    class_names: []
    pretrain: true
    temperature: 3.0
    arch: resnet18
    no_pool: false
    adv_validation_iters: 100
    cfol_sampling: false
    bottleneck_dim: 1024
    checkpoint_path: /home/mielonen/robust-domain-adaptation/model_registry/checkpoints
    
