experiment:
  target_dataset:
    class_name: MNIST
    path: ~/robust-domain-adaptation/dataset_registry/data/mnist
    train:
      name: MNIST-t
      transform_args: {} 
    validate:
      name: MNIST-v
      transform_args: {} 
  source_dataset:
    class_name: MNIST_M
    path: ~/robust-domain-adaptation/dataset_registry/data/mnistm
    train: 
      name: MNISTM-t
      transform_args: {} 
    validate:
      name: MNISTM-v
      transform_args: {} 
  models:
    - simpleDiscriminator
    - simpleGenerator
    - simpleClassifier 
  routines:
    - train_pixel_da:
        discriminator: simpleDiscriminator
        generator: simpleGenerator
        classifier: simpleClassifier
        source_train: MNIST-t
        target_train: MNISTM-t
        source_val: MNIST-v
        target_val: MNISTM-v
  global_params:
    num_epochs: 50
    batch_size: 64
    lr: 0.0002
    b1: 0.5
    b2: 0.999
    n_cpu: 8
    n_residual_blocks: 6
    latent_dim: 10
    img_size: 32
    channels: 3
    class_names: []
    n_classes: 10