experiment:
  source_dataset:
    class_name: VISDA17_synthetic
    path: /home/mielonen/robust-domain-adaptation/dataset_registry/data/visda2017
    train:
      name: visdas-t
      transform_args:
        resizing: cen.crop
    validate:
      name: visdas-v
      transform_args: {}
  target_dataset:
    class_name: VISDA17_real
    path: /home/mielonen/robust-domain-adaptation/dataset_registry/data/visda2017
    train: 
      name: visdar-t
      transform_args:
        resizing: cen.crop
    validate:
      name: visdar-v
      transform_args: {}
  models:
    - simpleDiscriminator
    - simpleGenerator
    - simpleClassifier 
  routines:
    - train_pixel_da:
        discriminator: simpleDiscriminator
        generator: simpleGenerator
        classifier: simpleClassifier
        source_train: visdas-t
        target_train: visdar-t
        source_val: visdas-v
        target_val: visdar-v
  global_params:
    num_epochs: 1
    batch_size: 64
    lr: 0.0002
    b1: 0.5
    b2: 0.999
    n_cpu: 8
    n_residual_blocks: 6
    latent_dim: 1024
    img_size: 224
    channels: 3
    n_classes: 10
    class_names:
      - zero
      - one
      - two 
      - three 
      - four 
      - five 
      - six 
      - seven
      - eight
      - nine 